#include "program.h"
#include <QTimer>
#include <QVBoxLayout>
#include <QGridLayout>
#include <QLabel>
Program::Program() {
    setupUIComponents();
    setupLayout();
    setupThreads();
    setupConnections();
    setupTimer();
}

void Program::setupUIComponents(){
    // Creating list boxes
    listBox1 = new QListWidget(this);
    listBox2 = new QListWidget(this);
    listBox3 = new QListWidget(this);

    // Creating labels
    thread1Label = new QLabel("Thread 1 (Stopped)", this);
    thread2Label = new QLabel("Thread 2", this);
    thread3Label = new QLabel("Thread 3 (Stopped)", this);

    // Setting alignment for labels
    thread1Label->setAlignment(Qt::AlignCenter);
    thread2Label->setAlignment(Qt::AlignCenter);
    thread3Label->setAlignment(Qt::AlignCenter);
}
void Program::setupLayout(){
    // Creating layout
    QGridLayout* gridLayout = new QGridLayout(this);

    // Setting widget sizes
    listBox1->setMinimumSize(150, 200);
    listBox2->setMinimumSize(150, 200);
    listBox3->setMinimumSize(150, 200);

    // Setting scalable size policies
    thread1Label->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
    thread2Label->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
    thread3Label->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);

    // Configure grid layout
    gridLayout->setColumnStretch(0, 1);
    gridLayout->setColumnStretch(1, 1);
    gridLayout->setColumnStretch(2, 1);
    gridLayout->setRowStretch(0, 0);
    gridLayout->setRowStretch(1, 1);
    gridLayout->setRowStretch(2, 0);

    // Add widgets to layout
    gridLayout->addWidget(thread1Label, 0, 0);
    gridLayout->addWidget(thread2Label, 0, 1);
    gridLayout->addWidget(thread3Label, 0, 2);

    gridLayout->addWidget(listBox1, 1, 0);
    gridLayout->addWidget(listBox2, 1, 1);
    gridLayout->addWidget(listBox3, 1, 2);

    startStopButton1 = new QPushButton("Start/Stop Thread 1", this);
    startStopButton3 = new QPushButton("Start/Stop Thread 3", this);

    // Set button sizes
    startStopButton1->setMinimumSize(100, 40);
    startStopButton3->setMinimumSize(100, 40);

    gridLayout->addWidget(startStopButton1, 2, 0);
    gridLayout->addWidget(startStopButton3, 2, 2);
}
void Program::setupThreads(){
    thread1 = new Thread1();  // Thread for generating numbers
    thread2 = new Thread2();  // Thread for managing the queue
    thread3 = new Thread3(thread2);  // Thread for consuming numbers
}
void Program::setupConnections(){
    // Connect signals for UI buttons
    connect(startStopButton1, &QPushButton::clicked, this, &Program::toggleThread1);
    connect(startStopButton3, &QPushButton::clicked, this, &Program::toggleThread3);

    // Connect signals between threads and UI updates
    connect(thread1, &Thread1::numberGenerated, this, &Program::addNum);
    connect(thread3, &Thread3::numberConsumed, this, &Program::consumeNum);
}
void Program::setupTimer(){
    // Setting up a timer to refresh the UI
    QTimer* timer = new QTimer(this);
    connect(timer, &QTimer::timeout, this, &Program::updateUI);
    timer->start(333);  // Trigger every 333 ms
}

// Updates the UI components (ListBoxes) every time the timer triggers
// It refreshes the display for all three threads' list boxes
void Program::updateUI()
{
    updateListBox1();
    updateListBox2();
    updateListBox3();
}

void Program::updateListBox1() {
    QMutexLocker locker(&mutex);  // Lock the mutex for thread safety
    // Loop through the generatedNumsBuffer and add new numbers to the list box
    while (!generatedNumsBuffer.isEmpty()) {

        // Taking the first number from the buffer and add it to the list box
        int num = generatedNumsBuffer.takeFirst();
        listBox1->addItem(QString::number(num));
    }
    listBox1->scrollToBottom();
}

void Program::updateListBox2(){
    listBox2->clear();
    for (int num : thread2->getNumbers()) {
        listBox2->addItem(QString::number(num));
    }
}
void Program::updateListBox3() {
    QMutexLocker locker(&mutex);  // Lock the mutex for thread safety
    // Loop through the generatedNumsBuffer and add new numbers to the list box
    while (!consumedNumsBuffer.isEmpty()) {
        // Take the first number from the buffer and add it to the list box
        int num = consumedNumsBuffer.takeFirst();
        listBox3->addItem(QString::number(num));
    }
    listBox3->scrollToBottom();
}

// This method handles the addition of a number generated by Thread1
// It adds the number to a temporary buffer (generatedNumsBuffer) and
// sends the number to the queue manager (thread2)
void Program::addNum(int num)
{
    QMutexLocker locker(&mutex);  // Lock the mutex for thread safety
    generatedNumsBuffer.push_back(num);
    thread2->addNumber(num);
}

// This method handles the consumption of a number by Thread3
// It adds the consumed number to the buffer (consumedNumsBuffer)
void Program::consumeNum(int num)
{
    QMutexLocker locker(&mutex);  // Lock the mutex for thread safety
    consumedNumsBuffer.push_back(num);
}

// Toggles the start/stop state of Thread1 when the button is clicked
// If the thread is running, it will stop and quit. If it is not running, the thread will start
void Program::toggleThread1(){
    if (thread1->running) {
        thread1->running = false;
        thread1->quit();
    } else {
        thread1->running = true;
        thread1->start();
    }
    updateThreadLabels();  // Update the label to reflect the thread state
}

// Toggles the start/stop state of Thread3 when the button is clicked
// Works similarly to `toggleThread1`, either stopping or starting Thread3
void Program::toggleThread3(){
    if (thread3->running) {
        thread3->running = false;
        thread3->quit();
    } else {
        thread3->running = true;
        thread3->start();
    }
    updateThreadLabels();  // Update the label to reflect the thread state
}

// Updates the labels on the UI to show the running/stopped state of Thread1 and Thread3
// This gives visual feedback to the user about the current state of the threads
void Program::updateThreadLabels()
{
    if(thread1->running) { thread1Label->setText("Thread 1 (Running)"); }
    else                 { thread1Label->setText("Thread 1 (Stopped)"); }

    if(thread3->running) { thread3Label->setText("Thread 3 (Running)"); }
    else                 { thread3Label->setText("Thread 3 (Stopped)"); }
}
